# Metadata:
#   Creation Date: 2024/5/14 05:08
#   Last Update Date: 2024/10/07 00:20
#   Author: git@xiaobo.tw
name: Python workflows (for hackItInterviewer)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask application
      env:
        FLASK_APP: run.py
        FLASK_ENV: development
      run: |
        set -e
        if sudo lsof -i:5000; then
          echo "Port 5000 is already in use"
          exit 1
        fi
        sudo --preserve-env=PATH,FLASK_APP,FLASK_ENV nohup python run.py > flask.log 2>&1 &
        sleep 10
        if ! pgrep -f "python run.py"; then
          echo "Failed to start Flask application."
          sudo cat flask.log
          exit 1
        fi
        # Testing the /webhook endpoint instead of homepage
        if [ "$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1/webhook)" -ne 404 ]; then
          echo "Flask application is running, but /webhook returned a non-expected status code."
          sudo cat flask.log
          exit 1
        else
          echo "Flask application is running successfully."
        fi

    - name: Show Flask log
      if: failure()
      run: |
        echo "Flask log:"
        sudo cat flask.log
